Pantalla registro asistencia
RowBlackGhost005/Attendance-Control pull request #2
Opened 2023-11-10 02:36 UTC by kevinrios23

#UH1-T5 - Pantalla de registro de asistencia (Seleccion de fecha de asistencia)

2023-11-13 01:25 UTC, fcampoa requested changes

2023-11-13 01:25 UTC, fcampoa commented on src/main/java/frames/registro_asistencia.java
> +        btn_importar_csv.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_excel.png")); // NOI1
esta ruta tiene que ser relativa, no absoluta, en este caso, basta con que pongas "img/icono_excel.png"

2023-11-13 01:25 UTC, fcampoa commented on src/main/java/frames/registro_asistencia.java
> +        btn_guardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_guardar.png")); // NOI18N
mismo comentario esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:25 UTC, fcampoa commented on src/main/java/frames/registro_asistencia.java
> +        btn_cancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_regresar.png")); // NOI18
mismo comentario esta ruta tiene que ser relativa, no absoluta

2023-11-13 20:50 UTC, kevinrios23 commented on src/main/java/frames/registro_asistencia.java
> +        btn_importar_csv.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_excel.png")); // NOI1
Listo

2023-11-17 00:49 UTC, fcampoa approved these changes

2023-11-18 16:54 UTC, merged