Pantalla registro cruso
RowBlackGhost005/Attendance-Control pull request #3
Opened 2023-11-10 02:37 UTC by kevinrios23

# UH6 - T9 - Pantalla de registro de curso

2023-11-13 01:27 UTC, fcampoa requested changes

2023-11-13 01:27 UTC, fcampoa commented on src/main/java/frames/cursos_registrados.java
> +        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_eliminar_small.png")); // NOI
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:27 UTC, fcampoa commented on src/main/java/frames/cursos_registrados.java
> +        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_regresar_small.png")); // NOI
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:27 UTC, fcampoa commented on src/main/java/frames/cursos_registrados.java
> +        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_editar.png")); // NOI18N
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:27 UTC, fcampoa commented on src/main/java/frames/cursos_registrados.java
> +        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_agregar_small.png")); // NOI1
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:27 UTC, fcampoa commented on src/main/java/frames/cursos_registrados.form
> +              <Image iconType="2" name="C:\Users\Kevin Rios\Desktop\Metodologias Agiles\Proyecto Agiles\Attendance-Control\src\main\java\img\icono_eliminar_small.png"/>
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:27 UTC, fcampoa commented on src/main/java/frames/cursos_registrados.form
> +              <Image iconType="2" name="C:\Users\Kevin Rios\Desktop\Metodologias Agiles\Proyecto Agiles\Attendance-Control\src\main\java\img\icono_editar.png"/>
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:27 UTC, fcampoa commented on src/main/java/frames/cursos_registrados.form
> +              <Image iconType="2" name="C:\Users\Kevin Rios\Desktop\Metodologias Agiles\Proyecto Agiles\Attendance-Control\src\main\java\img\icono_agregar_small.png"/>
esta ruta tiene que ser relativa, no absoluta

2023-11-13 20:49 UTC, kevinrios23 commented on src/main/java/frames/cursos_registrados.java
> +        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_eliminar_small.png")); // NOI
Listo

2023-11-17 00:48 UTC, fcampoa approved these changes

2023-11-18 16:53 UTC, merged