Pantalla grupos registrados
RowBlackGhost005/Attendance-Control pull request #4
Opened 2023-11-10 02:37 UTC by kevinrios23

#UH6 - T11 - Pantalla de grupos registrados

2023-11-13 01:29 UTC, fcampoa requested changes

2023-11-13 01:29 UTC, fcampoa commented on src/main/java/frames/grupos_registrados.form
> +              <Image iconType="2" name="C:\Users\Kevin Rios\Desktop\Metodologias Agiles\Proyecto Agiles\Attendance-Control\src\main\java\img\icono_agregar_small.png"/>
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:29 UTC, fcampoa commented on src/main/java/frames/grupos_registrados.form
> +              <Image iconType="2" name="C:\Users\Kevin Rios\Desktop\Metodologias Agiles\Proyecto Agiles\Attendance-Control\src\main\java\img\icono_regresar_small.png"/>
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:29 UTC, fcampoa commented on src/main/java/frames/grupos_registrados.form
> +              <Image iconType="2" name="C:\Users\Kevin Rios\Desktop\Metodologias Agiles\Proyecto Agiles\Attendance-Control\src\main\java\img\icono_consultar_small.png"/>
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:29 UTC, fcampoa commented on src/main/java/frames/grupos_registrados.java
> +        btn_editar_grupo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_editar.png")); // NOI
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:29 UTC, fcampoa commented on src/main/java/frames/grupos_registrados.java
> +        btn_agregar_grupo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_agregar_small.png"))
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:29 UTC, fcampoa commented on src/main/java/frames/grupos_registrados.java
> +        btn_regresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_regresar_small.png")); //
esta ruta tiene que ser relativa, no absoluta

2023-11-13 01:29 UTC, fcampoa commented on src/main/java/frames/grupos_registrados.java
> +        btn_consultar_grupo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin Rios\\Desktop\\Metodologias Agiles\\Proyecto Agiles\\Attendance-Control\\src\\main\\java\\img\\icono_consultar_small.pn
esta ruta tiene que ser relativa, no absoluta

2023-11-13 20:50 UTC, kevinrios23 commented on src/main/java/frames/grupos_registrados.form
> +              <Image iconType="2" name="C:\Users\Kevin Rios\Desktop\Metodologias Agiles\Proyecto Agiles\Attendance-Control\src\main\java\img\icono_agregar_small.png"/>
Listo

2023-11-17 00:49 UTC, fcampoa approved these changes

2023-11-18 16:52 UTC, merged